docs/index.html, index.bs
This proposed new version is the result of major restructuring and simplification of the spec text, with some technical clarifications.
=> Proposed new version

index.bs, index.html
Used bikeshed version https://github.com/tabatkins/bikeshed/commit/018be3f805d3272ce699a232398d6e3902d1ea8d
Fix ids, links (difference between a property surrounded by `'` and definitions) ...
=> fix bikeshed warnings 

index.bs, index.html
adding an overview and a common constraints subsections to the profiles section, for readability and references
=> restructuring the profiles section

index.bs, index.html
=> introduce brand for intra-only sequences

index.bs, index.html
=> clarify support for multi-layer images (#18)

index.bs, index.html
=> Clarify that multi-layered images are supported

index.bs, index.html
=> clarify that depth map images can be coded

index.bs, index.html
=> clarify profiles for auxiliary image items or sequences

index.bs, index.html
update date, sub-title, and remove warning
=> Preparation for publication

index.bs, index.html
closes #76
***
<a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-avif/pull/100.html" title="Last updated on Oct 22, 2020, 9:11 PM UTC (377a643)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-avif/100/faa2436...377a643.html" title="Last updated on Oct 22, 2020, 9:11 PM UTC (377a643)">Diff</a>
=> Rephrase sentence describing auxiliary images and master image profile

index.bs, index.html
closes #79
***
<a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-avif/pull/116.html" title="Last updated on Oct 27, 2020, 5:40 PM UTC (f38f221)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-avif/116/3491f6f...f38f221.html" title="Last updated on Oct 27, 2020, 5:40 PM UTC (f38f221)">Diff</a>
=> add support for the cclv property 

testFiles/Netflix/index.html
=> add index.html for Netflix files

index.bs, index.html
closes #124
***
<a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-avif/pull/125.html" title="Last updated on Jan 6, 2021, 6:03 PM UTC (75b7b68)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-avif/125/9459ef4...75b7b68.html" title="Last updated on Jan 6, 2021, 6:03 PM UTC (75b7b68)">Diff</a>
=> add restriction on transformative properties in derivation chains

index.bs
closes #154 
closes #158 
closes #160
***
<a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-avif/pull/171.html" title="Last updated on Oct 20, 2021, 12:29 AM UTC (2240ac5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-avif/171/db736e7...2240ac5.html" title="Last updated on Oct 20, 2021, 12:29 AM UTC (2240ac5)">Diff</a>
=> Editorial changes

index.bs, logo.include
For warnings and logo update
***
<a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-avif/pull/176.html" title="Last updated on Dec 3, 2021, 1:14 AM UTC (ed05cdf)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-avif/176/54dfd36...ed05cdf.html" title="Last updated on Dec 3, 2021, 1:14 AM UTC (ed05cdf)">Diff</a>
=> Apply bikeshed boilerplate update

index.bs, v1.1.0.html
updating bikeshed file to Final Deliverable, generating snapshot and tweaking header to link various versions
***
<a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-avif/pull/192.html" title="Last updated on May 5, 2022, 6:46 PM UTC (f50c58d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-avif/192/98ef5db...f50c58d.html" title="Last updated on May 5, 2022, 6:46 PM UTC (f50c58d)">Diff</a>
=> Generating v1.1.0 version

index.bs
This fixes #218.
@tidoust, please take a look so that I understood the issue correctly.
***
<a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-avif/pull/223.html" title="Last updated on Sep 5, 2024, 8:25 AM UTC (b1e27f9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-avif/223/8ebeb5f...b1e27f9.html" title="Last updated on Sep 5, 2024, 8:25 AM UTC (b1e27f9)">Diff</a>
=> Fix use of <dfn value> and some indenting.

index.bs
This fixes #214.
***
<a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-avif/pull/222.html" title="Last updated on Sep 5, 2024, 9:36 AM UTC (39ebe57)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-avif/222/79bd06f...39ebe57.html" title="Last updated on Sep 5, 2024, 9:36 AM UTC (39ebe57)">Diff</a>
=> Add asserts for shoulds and shalls

index.bs
This closes #157
***
<a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-avif/pull/238.html" title="Last updated on Sep 12, 2024, 7:16 AM UTC (8c8ccdc)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-avif/238/bbeec5f...8c8ccdc.html" title="Last updated on Sep 12, 2024, 7:16 AM UTC (8c8ccdc)">Diff</a>
=> Change 'ispe' width to correspond to UpscaledWidth

index.bs
This closes #231
***
<a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-avif/pull/233.html" title="Last updated on Sep 12, 2024, 7:38 AM UTC (9dda427)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-avif/233/b2b2a23...9dda427.html" title="Last updated on Sep 12, 2024, 7:38 AM UTC (9dda427)">Diff</a>
=> Update list of other item properties

index.bs
This closes #242
***
<a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-avif/pull/243.html" title="Last updated on Sep 17, 2024, 10:16 AM UTC (cf5fdcb)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-avif/243/01e3ea3...cf5fdcb.html" title="Last updated on Sep 17, 2024, 10:16 AM UTC (cf5fdcb)">Diff</a>
=> Reword av1C vs pixi conformance

index.bs
This closes #237
***
<a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-avif/pull/239.html" title="Last updated on Sep 17, 2024, 10:22 AM UTC (a9d4bb5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-avif/239/24508d6...a9d4bb5.html" title="Last updated on Sep 17, 2024, 10:22 AM UTC (a9d4bb5)">Diff</a>
=> Add tmap and altr text

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-avif/pull/249.html" title="Last updated on Sep 23, 2024, 3:28 PM UTC (a534bc0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-avif/249/b6758ca...a534bc0.html" title="Last updated on Sep 23, 2024, 3:28 PM UTC (a534bc0)">Diff</a>
=> Add Wan-Teh Chang as an editor

index.bs
Also add references.
***
<a href="https://pr-preview.s3.amazonaws.com/y-guyon/av1-avif/pull/257.html" title="Last updated on Oct 10, 2024, 8:51 AM UTC (52dd13d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-avif/257/fa78f2b...y-guyon:52dd13d.html" title="Last updated on Oct 10, 2024, 8:51 AM UTC (52dd13d)">Diff</a>
=> Add references, fix wording and format in clauses 1,2

index.bs
along other supported features.
***
<a href="https://pr-preview.s3.amazonaws.com/y-guyon/av1-avif/pull/258.html" title="Last updated on Oct 10, 2024, 9:01 AM UTC (d6ea9a0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-avif/258/506c1e4...y-guyon:d6ea9a0.html" title="Last updated on Oct 10, 2024, 9:01 AM UTC (d6ea9a0)">Diff</a>
=> Add sato, alpha, depth, progressive in Scope

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/y-guyon/av1-avif/pull/266.html" title="Last updated on Oct 18, 2024, 12:09 PM UTC (196a2fe)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-avif/266/727501a...y-guyon:196a2fe.html" title="Last updated on Oct 18, 2024, 12:09 PM UTC (196a2fe)">Diff</a>
=> Indent notes as the list items they refer to

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/y-guyon/av1-avif/pull/267.html" title="Last updated on Oct 18, 2024, 12:38 PM UTC (4f37e1c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-avif/267/727501a...y-guyon:4f37e1c.html" title="Last updated on Oct 18, 2024, 12:38 PM UTC (4f37e1c)">Diff</a>
=> Remove inconsistent dots in 9.1.2

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/wantehchang/av1-avif/pull/279.html" title="Last updated on Oct 22, 2024, 10:05 PM UTC (89e8490)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-avif/279/439b57e...wantehchang:89e8490.html" title="Last updated on Oct 22, 2024, 10:05 PM UTC (89e8490)">Diff</a>
=> Add the word "bits" to the amount of shift

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/wantehchang/av1-avif/pull/280.html" title="Last updated on Oct 22, 2024, 10:08 PM UTC (360a6cc)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-avif/280/439b57e...wantehchang:360a6cc.html" title="Last updated on Oct 22, 2024, 10:08 PM UTC (360a6cc)">Diff</a>
=> Add the word "added" to "parentheses for clarity"

index.bs
The 'colr' box specifies color information.
***
<a href="https://pr-preview.s3.amazonaws.com/wantehchang/av1-avif/pull/276.html" title="Last updated on Oct 23, 2024, 4:00 PM UTC (fc6581f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-avif/276/2acad7e...wantehchang:fc6581f.html" title="Last updated on Oct 23, 2024, 4:00 PM UTC (fc6581f)">Diff</a>
=> Add the word "color"

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/wantehchang/av1-avif/pull/284.html" title="Last updated on Oct 23, 2024, 4:19 PM UTC (ba205ab)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-avif/284/486d3ff...wantehchang:ba205ab.html" title="Last updated on Oct 23, 2024, 4:19 PM UTC (ba205ab)">Diff</a>
=> Minor edits and punctuation fixes in sato examples

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-avif/pull/296.html" title="Last updated on Jan 10, 2025, 11:15 AM UTC (626a9df)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-avif/296/6820e20...626a9df.html" title="Last updated on Jan 10, 2025, 11:15 AM UTC (626a9df)">Diff</a>
=> Update date and status to WGA

index.bs
This closes #299
***
<a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-avif/pull/300.html" title="Last updated on Jan 20, 2025, 12:25 PM UTC (338bdb1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-avif/300/46332a5...338bdb1.html" title="Last updated on Jan 20, 2025, 12:25 PM UTC (338bdb1)">Diff</a>
=> Make asserts between profiles unique

index.bs
Update the HEIF, ISOBMFF, and MIAF references to the latest versions.
=> Update HEIF,ISOBMFF,MIAF references to new version

index.bs
Closes #307
***
<a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-avif/pull/314.html" title="Last updated on Aug 20, 2025, 4:56 PM UTC (0c6268f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-avif/314/3ba0ec7...0c6268f.html" title="Last updated on Aug 20, 2025, 4:56 PM UTC (0c6268f)">Diff</a>
=> Update HEIF to point to 3ed AMD1
