AOMediaCodec/av1-avif

- biblio.json
- docs/index.html
- index.bs
Specification is restructured to separate instructions on how to build an HEIF file that can wrap AV1 still images from the profile definition for a version 1.0 AVIF reader. I also removed text that was a restatement of items found in either HEIF or ISO-BMFF.
> Rework document into two part: separate HEIF construction details from AVIF profile

- index.bs
**Motivation**
The AV1 spec mentions to header fields that have meaning for still pictures. The `still_picture` field indicates that the stream consists of exactly one frame. This can be used by the decoder to avoid allocating resources for inter-frame decoding. Therefore, it's mentioned as must (shall).
The `reduced_still_picture_header` indicates that the header is not including fields that only have value for inter-frame encodings. Leaving them out saves size and therefore it is recommended (should). As described in https://aomediacodec.github.io/av1-spec/av1-spec.pdf on page 113, it might be set to 0 to allow for efficient extracting frames from an AV1 video.
**Changes**
Added two paragraphs in section 4 "Image Data"
As mentioned in https://github.com/AOMediaCodec/av1-avif/issues/7 …
> Add still_picture and reduced_still_picture_header references 

- biblio.json
- index.bs
- index.html
- Defined Baseline and Advanced profiles for the file format. Moved some requirements from the main section to the profile sections. This partially addresses #16.
- The relationship between this spec and MIAF was a bit unclear. I tried to address this in the definitions of the two profiles.
- Added file extension and MIME type definitions. This closes #20.
- I define a separate brand, file extension and MIME type for image sequences. This closes #9.
- Made the spec separate between pict tracks and video tracks. This closes #19.
- Made still_picture = 1 recommended instead of mandatory. This closes #12 and also closes #14.
I am having some trouble with the Bikeshed syntax. It is currently giving me some warnings and I think I need help clearing that up.
> Addressed various issues, some restructuring

- index.bs
- index.html
The idea is to replace 'extend' because I find it confusing to extend MIAF given that MIAF is MPEG and based on AVC/HEVC. I wanted to say that we reuse the constraints defined in MIAF and that we followed the approach of MIAF to define AV1-based profiles.
> update abstract to clarify relationship with MIAF

- index.bs
- index.html
removing commented text
restructuring brand requirements as bullet points
clarifying use of HEIF brands
adding examples
It has conflicts with the changes on MIME types. Will fix them once #25 is merged.
> Various editorial changes on brands

- index.bs
Also, add a newline at the end, because the Github does that automatically
***
<a href="https://pr-preview.s3.amazonaws.com/baumanj/av1-avif/pull/66.html" title="Last updated on Dec 20, 2019, 8:29 PM UTC (41f22f5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-avif/66/9be5a5a...baumanj:41f22f5.html" title="Last updated on Dec 20, 2019, 8:29 PM UTC (41f22f5)">Diff</a>
> Fix transposed characters in TrackTypeBox link

- index.bs
- index.html
close #93
***
<a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-avif/pull/101.html" title="Last updated on Sep 3, 2020, 3:27 PM UTC (bfa4060)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-avif/101/66e9d59...bfa4060.html" title="Last updated on Sep 3, 2020, 3:27 PM UTC (bfa4060)">Diff</a>
> constrain auxiliary images to be full range, and ignore colr for alpha planes

- index.bs
- index.html
closes #97
***
<a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-avif/pull/115.html" title="Last updated on Oct 27, 2020, 5:44 PM UTC (85111d4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-avif/115/b951a43...85111d4.html" title="Last updated on Oct 27, 2020, 5:44 PM UTC (85111d4)">Diff</a>
> fix links for externally-defined terms

- index.bs
- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-avif/pull/127.html" title="Last updated on Feb 4, 2021, 9:14 PM UTC (3c74b9f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-avif/127/d1220be...3c74b9f.html" title="Last updated on Feb 4, 2021, 9:14 PM UTC (3c74b9f)">Diff</a>
> Replace Media Type section with link to official IANA registration

- index.bs
- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-avif/pull/137.html" title="Last updated on Mar 18, 2021, 12:42 AM UTC (51cd677)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-avif/137/7536f4b...51cd677.html" title="Last updated on Mar 18, 2021, 12:42 AM UTC (51cd677)">Diff</a>
> Correct usage of level vs. level index

- index.bs
- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-avif/pull/147.html" title="Last updated on Apr 28, 2021, 5:04 PM UTC (e4515a6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-avif/147/781b787...e4515a6.html" title="Last updated on Apr 28, 2021, 5:04 PM UTC (e4515a6)">Diff</a>
> Make a1op a simple box

- index.bs
Fix `FATAL ERROR: &lt;pre class=anchors> anchor was defined with a local link '#biblio-heif'. Please use urlPrefix and/or url to define an external URL`.
(update)
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Nov 23, 2022, 4:30 AM UTC)_.
<details>
<summary>More</summary>
PR Preview relies on a number of web services to run. There seems to be an issue with the following one:
:rotating_light: [CSS Spec Preprocessor](https://api.csswg.org/bikeshed/) - CSS Spec Preprocessor is the web service used to build Bikeshed specs.
:link: [Related URL](https://api.csswg.org/bikeshed/?url=https%3A%2F%2Fraw.githubusercontent.com%2FAOMediaCodec%2Fav1-avif%2Fbde4abda08b7934e7b78da2de4d1f7b1157f4548%2Findex.bs&md-warning=not%20ready)
```
Error running …
```
> Fix "anchor defined with local link" Bikeshed err

- index.bs
Fix nits.
***
<a href="https://pr-preview.s3.amazonaws.com/y-guyon/av1-avif/pull/204.html" title="Last updated on Jun 26, 2024, 2:27 PM UTC (8c1f8b7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-avif/204/ce1174e...y-guyon:8c1f8b7.html" title="Last updated on Jun 26, 2024, 2:27 PM UTC (8c1f8b7)">Diff</a>
> Make indent and formatting consistent

- index.bs
Closes #167.
This is a rebase and fixup of PR #170.
The section on box requirements for sequences has been removed until someone has taken the time to fully go through it.
***
<a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-avif/pull/225.html" title="Last updated on Sep 11, 2024, 5:45 PM UTC (ea337df)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-avif/225/b9ea3d8...ea337df.html" title="Last updated on Sep 11, 2024, 5:45 PM UTC (ea337df)">Diff</a>
> Add list of boxes

- index.bs
This closes #182
***
<a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-avif/pull/229.html" title="Last updated on Sep 11, 2024, 5:49 PM UTC (2e594a0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-avif/229/c1f956f...2e594a0.html" title="Last updated on Sep 11, 2024, 5:49 PM UTC (2e594a0)">Diff</a>
> Add "per item" to item property definitions

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-avif/pull/227.html" title="Last updated on Sep 11, 2024, 5:59 PM UTC (cf76ce5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-avif/227/cc68618...cf76ce5.html" title="Last updated on Sep 11, 2024, 5:59 PM UTC (cf76ce5)">Diff</a>
> Relax transformative properties constraint on derivation chains to only apply to 'grid' items

- index.bs
This closes #156
***
<a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-avif/pull/234.html" title="Last updated on Sep 12, 2024, 7:32 AM UTC (7681a1c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-avif/234/7a095c1...7681a1c.html" title="Last updated on Sep 12, 2024, 7:32 AM UTC (7681a1c)">Diff</a>
> Fix typo in av1C text discussing metadata OBUs

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/y-guyon/av1-avif/pull/228.html" title="Last updated on Sep 17, 2024, 11:39 AM UTC (f688785)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-avif/228/3d2d175...y-guyon:f688785.html" title="Last updated on Sep 17, 2024, 11:39 AM UTC (f688785)">Diff</a>
> Replace recommendations regarding still picture flags in image items by a note

- index.bs
Make it obvious that AVIF also supports 16-bit.
***
<a href="https://pr-preview.s3.amazonaws.com/y-guyon/av1-avif/pull/245.html" title="Last updated on Sep 18, 2024, 7:50 AM UTC (a5d301c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-avif/245/70d14e6...y-guyon:a5d301c.html" title="Last updated on Sep 18, 2024, 7:50 AM UTC (a5d301c)">Diff</a>
> Add Sample Transform rationale

- index.bs
Increase unary operator range to 64+ to leave room for more operand token types.
***
<a href="https://pr-preview.s3.amazonaws.com/y-guyon/av1-avif/pull/246.html" title="Last updated on Sep 20, 2024, 11:04 AM UTC (0defe35)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-avif/246/b21779d...y-guyon:0defe35.html" title="Last updated on Sep 20, 2024, 11:04 AM UTC (0defe35)">Diff</a>
> Specify Sample Transform syntax versioning

- index.bs
Clarify the comments of the SampleTransform syntax code snippet. Refactor Table 2 columns.
***
<a href="https://pr-preview.s3.amazonaws.com/y-guyon/av1-avif/pull/248.html" title="Last updated on Sep 20, 2024, 11:59 AM UTC (c3897cc)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-avif/248/b6758ca...y-guyon:c3897cc.html" title="Last updated on Sep 20, 2024, 11:59 AM UTC (c3897cc)">Diff</a>
> Replace explicit input_image_item_index by token

- index.bs
This closes #188
***
<a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-avif/pull/232.html" title="Last updated on Sep 25, 2024, 7:00 AM UTC (01fcade)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-avif/232/e82a232...01fcade.html" title="Last updated on Sep 25, 2024, 7:00 AM UTC (01fcade)">Diff</a>
> Add restriction on 'clap' property

- index.bs
This closes #169
***
<a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-avif/pull/240.html" title="Last updated on Sep 25, 2024, 7:07 AM UTC (4215905)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-avif/240/adc56d5...4215905.html" title="Last updated on Sep 25, 2024, 7:07 AM UTC (4215905)">Diff</a>
> Adopt MIAF shared constraints

- index.bs
This closes #244
***
<a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-avif/pull/251.html" title="Last updated on Sep 25, 2024, 5:45 PM UTC (b9a7de9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-avif/251/1796dae...b9a7de9.html" title="Last updated on Sep 25, 2024, 5:45 PM UTC (b9a7de9)">Diff</a>
> Clean up use of dfn and linking

- index.bs
This closes #247.
***
<a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-avif/pull/250.html" title="Last updated on Sep 27, 2024, 8:42 AM UTC (1c5c7cd)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-avif/250/7f87801...1c5c7cd.html" title="Last updated on Sep 27, 2024, 8:42 AM UTC (1c5c7cd)">Diff</a>
> Clarify that non-essential item properties may use other versions

- index.bs
This closes #254
***
<a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-avif/pull/255.html" title="Last updated on Sep 27, 2024, 8:55 AM UTC (ad3bf87)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-avif/255/434dbe1...ad3bf87.html" title="Last updated on Sep 27, 2024, 8:55 AM UTC (ad3bf87)">Diff</a>
> Remove "value" from sato definition

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-avif/pull/256.html" title="Last updated on Oct 16, 2024, 6:52 AM UTC (51a1b82)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-avif/256/e0e048e...51a1b82.html" title="Last updated on Oct 16, 2024, 6:52 AM UTC (51a1b82)">Diff</a>
> Fix final review comments from Leo

- index.bs
Already done for `SampleTransform`.
I find it improves the readability of the Syntax sections.
***
<a href="https://pr-preview.s3.amazonaws.com/y-guyon/av1-avif/pull/259.html" title="Last updated on Oct 18, 2024, 9:13 AM UTC (3e9e460)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-avif/259/727501a...y-guyon:3e9e460.html" title="Last updated on Oct 18, 2024, 9:13 AM UTC (3e9e460)">Diff</a>
> Use Markdown syntax coloring for code snippets

- index.bs
To make sure the first sentence of each derived image item section is rendered in a similar way.
***
<a href="https://pr-preview.s3.amazonaws.com/y-guyon/av1-avif/pull/261.html" title="Last updated on Oct 18, 2024, 9:57 AM UTC (f292611)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-avif/261/727501a...y-guyon:f292611.html" title="Last updated on Oct 18, 2024, 9:57 AM UTC (f292611)">Diff</a>
> Consistently use dfn noexport for derived items

- index.bs
Same as for Operating Point Selector Property sections.
***
<a href="https://pr-preview.s3.amazonaws.com/y-guyon/av1-avif/pull/262.html" title="Last updated on Oct 18, 2024, 9:57 AM UTC (84a1f65)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-avif/262/727501a...y-guyon:84a1f65.html" title="Last updated on Oct 18, 2024, 9:57 AM UTC (84a1f65)">Diff</a>
> Remove Sample Transform sections from TOC

- index.bs
Use box names instead of some property 4CC types.
Add a comment about creating the stack in the Syntax section.
***
<a href="https://pr-preview.s3.amazonaws.com/y-guyon/av1-avif/pull/263.html" title="Last updated on Oct 21, 2024, 2:33 PM UTC (910cc39)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-avif/263/b1a66af...y-guyon:910cc39.html" title="Last updated on Oct 21, 2024, 2:33 PM UTC (910cc39)">Diff</a>
> Add references in the Sample Transform sections

- index.bs
This closes #268 and #270.
Changes:
- Change text to say that all the boxes in the table are in the 'meta' box
- Change layering to same levels as 9.1.1 table
- Remove containing box column
- Change text on box order
***
<a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-avif/pull/273.html" title="Last updated on Oct 23, 2024, 9:16 AM UTC (df6a1e3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-avif/273/439b57e...df6a1e3.html" title="Last updated on Oct 23, 2024, 9:16 AM UTC (df6a1e3)">Diff</a>
> Change optional boxes table layering

- index.bs
Fixes https://github.com/AOMediaCodec/av1-avif/issues/283
***
<a href="https://pr-preview.s3.amazonaws.com/y-guyon/av1-avif/pull/287.html" title="Last updated on Oct 23, 2024, 9:21 AM UTC (236edd2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-avif/287/439b57e...y-guyon:236edd2.html" title="Last updated on Oct 23, 2024, 9:21 AM UTC (236edd2)">Diff</a>
> Use precise dim/chan constraints in sato examples

- index.bs
Fixes https://github.com/AOMediaCodec/av1-avif/issues/278
***
<a href="https://pr-preview.s3.amazonaws.com/y-guyon/av1-avif/pull/288.html" title="Last updated on Oct 23, 2024, 11:02 AM UTC (6d9dc43)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-avif/288/7e5c8c7...y-guyon:6d9dc43.html" title="Last updated on Oct 23, 2024, 11:02 AM UTC (6d9dc43)">Diff</a>
> Gainmap and least signif should be hidden items

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/wantehchang/av1-avif/pull/286.html" title="Last updated on Oct 22, 2024, 11:55 PM UTC (02216ee)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-avif/286/439b57e...wantehchang:02216ee.html" title="Last updated on Oct 22, 2024, 11:55 PM UTC (02216ee)">Diff</a>
> Minor edits in Section 8 Profiles

- index.bs
Otherwise, it seems that it is the specifications that shall be respected.
Also make the second instance of this sentence more similar to the first instance.
***
<a href="https://pr-preview.s3.amazonaws.com/wantehchang/av1-avif/pull/275.html" title="Last updated on Oct 23, 2024, 3:45 PM UTC (be09d08)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-avif/275/a83f921...wantehchang:be09d08.html" title="Last updated on Oct 23, 2024, 3:45 PM UTC (be09d08)">Diff</a>
> Clarify it is the order that shall be respected

- index.bs
In prevision of the major_brand field of the FileTypeBox not needing to be repeated in the compatible_brands field.
***
<a href="https://pr-preview.s3.amazonaws.com/y-guyon/av1-avif/pull/289.html" title="Last updated on Oct 23, 2024, 3:55 PM UTC (83856d0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-avif/289/2acad7e...y-guyon:83856d0.html" title="Last updated on Oct 23, 2024, 3:55 PM UTC (83856d0)">Diff</a>
> Remove mentions of ftyp compatible_brands

- index.bs
Matches libavif behavior, see https://github.com/AOMediaCodec/libavif/blob/048488e0588b0543d122ec95ac1a4f54cc73285a/src/write.c#L3204-L3207.
***
<a href="https://pr-preview.s3.amazonaws.com/y-guyon/av1-avif/pull/265.html" title="Last updated on Oct 24, 2024, 9:20 AM UTC (7b3f4b9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-avif/265/2a57aca...y-guyon:7b3f4b9.html" title="Last updated on Oct 24, 2024, 9:20 AM UTC (7b3f4b9)">Diff</a>
> Remove avio brand recommendation

- index.bs
This closes #291.
I _think_ the output looks nicer at least. I also removed a redundant `<li>` tag and converted the NOTE to a bikeshed NOTE.
***
<a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-avif/pull/292.html" title="Last updated on Oct 25, 2024, 12:34 PM UTC (7089fa9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-avif/292/9c389bb...7089fa9.html" title="Last updated on Oct 25, 2024, 12:34 PM UTC (7089fa9)">Diff</a>
> Fix use of br tags in SATO examples

- index.bs
This is how "gain map" is spelled in ISO standards.
> Spell "gain map" as two words

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/wantehchang/av1-avif/pull/311.html" title="Last updated on Apr 28, 2025, 6:21 PM UTC (0186eb6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-avif/311/aaea3c9...wantehchang:0186eb6.html" title="Last updated on Apr 28, 2025, 6:21 PM UTC (0186eb6)">Diff</a>
> Correct misspelling "bistream" to "bitstream"
